1::SendText "Front elevation overview"
2::SendText "Right elevation overview"
3::SendText "Rear elevation overview"
4::SendText "Left elevation overview"
5::SendText "Hail Damage to"
6::SendText "No Damage to"
7::SendText "Overview"
8::SendText "Roof Overview"
9::SendText "Test Square overview"
0::SendText "Damage Totals"
-::SendText "Front Slope"
=::SendText "Back Slope"
q::SendText "Right Slope"
w::SendText "left Slope"
e::SendText "Living Room"
r::SendText "Kitchen"
t::SendText "Bedroom"
y::SendText "Bathroom"
u::SendText "Water Damage to ceiling"
a::SendText "Address Verification"
d::SendText "Downspout"
i::SendText "Mech Damage"
s::SendText "30-year laminate Roof Covering"
f::SendText "Single Layer, Drip Edge Installed"
g::SendText "Gutter"
h::SendText "Shingle condition shots"
j::SendText "Hail Damage Close-up"
c::SendText "Carrier to review reports and determine payment"
p::SendText "Roof pitch"

#SuspendExempt
~::Suspend
#SuspendExempt False
.::Reload
